apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-test-svc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  project: default
  source:
    path: test-svc/manifests/qa/
    repoURL: https://github.com/sinhasonalkumar/application-k8s-state.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   